apiVersion: v2
name: rusty-valkey-forward-auth
description: Helm chart for deploying the Rusty Valkey Forward Auth service.
type: application
version: 0.1.3
appVersion: "0.1.3"
keywords:
  - valkey
  - oauth2
  - forward-auth
  - rust
dependencies:
  - name: valkey
    version: 0.9.3
    repository: https://valkey.io/valkey-helm/
